name: CD - Deploy to Oracle Stage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ORACLE_STAGE_SSH_KEY  }}

      - name: Deploy to Oracle Server using SSH
        run: |
          # SSH로 서버에 접속하여 디렉터리 생성
          ssh -o StrictHostKeyChecking=no ubuntu@stage.skkutable.com "cd ~; sudo rm -rf skku-table-frontend; git clone https://github.com/skku-table/skku-table-frontend.git"

          # Docker Compose로 애플리케이션 실행
          ssh -o StrictHostKeyChecking=no ubuntu@stage.skkutable.com "cd ~/skku-table-frontend && docker compose pull && docker compose up -d"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ORACLE_STAGE_SSH_KEY }}
