name: CD - Deploy to Oracle Stage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH into Oracle and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: stage.skkutable.com
          username: ubuntu
          key: ${{ secrets.ORACLE_STAGE_SSH_KEY }}
          script: |
            # 디렉토리 없으면 생성
            mkdir -p ~/apps

            cd ~/apps

            # 레포 없으면 clone, 있으면 pull
            if [ ! -d "frontend" ]; then
              git clone git@github.com:skku-table/skku-table-frontend.git frontend
            else
              cd frontend
              git pull origin main
            fi

            cd ~/apps/frontend
            docker compose pull
            docker compose up -d
